// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShinyCounter.Data;

namespace ShinyCounter.Migrations
{
    [DbContext(typeof(ProfileContext))]
    [Migration("20200428030957_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShinyCounter.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("caught1")
                        .HasColumnType("bit");

                    b.Property<bool>("caught10")
                        .HasColumnType("bit");

                    b.Property<bool>("caught11")
                        .HasColumnType("bit");

                    b.Property<bool>("caught12")
                        .HasColumnType("bit");

                    b.Property<bool>("caught2")
                        .HasColumnType("bit");

                    b.Property<bool>("caught3")
                        .HasColumnType("bit");

                    b.Property<bool>("caught4")
                        .HasColumnType("bit");

                    b.Property<bool>("caught5")
                        .HasColumnType("bit");

                    b.Property<bool>("caught6")
                        .HasColumnType("bit");

                    b.Property<bool>("caught7")
                        .HasColumnType("bit");

                    b.Property<bool>("caught8")
                        .HasColumnType("bit");

                    b.Property<bool>("caught9")
                        .HasColumnType("bit");

                    b.Property<int>("counter")
                        .HasColumnType("int");

                    b.Property<int>("goal")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
